### ISSUE TITLE
requests package pinned too strict, causing Home Assistant unable to upgrade 

### ISSUE THREAD

**Issue by frenck** [broox/python-nuheat#13]
This library is pinning the `requests` dependency too strictly.

```
  install_requires=[
    'requests==2.28.1',
  ],
```

https://github.com/broox/python-nuheat/blob/41db294f2205822b25f14966af5b5086241e1591/setup.py#L33

As a result of that, any upstream project using this library, cannot upgrade `requests` to a newer version. Please ping a range or a minimal version that is required for this library instead.

Context: I ran into this when upgrading the `requests` package @ Home Assistant to 2.28.2, for which this package caused a conflict.

../Frenck

**Comment by broox** [comment]
@frenck this has been updated and pushed to pypi
