### ISSUE TITLE
"Cannot convert float to decimal" when firing simple script

### ISSUE THREAD

**Issue by yetdog** [broox/python-nuheat#2]
git cloned your project, and created nuheat.py:

```
from nuheat import NuHeat

# Initalize an API session with your login credentials
api = NuHeat("######", "######")
api.authenticate()

# Fetch a thermostat by serial number / ID. This can be found on the NuHeat website by selecting
# your thermostat and noting the Thermostat ID
thermostat = api.get_thermostat("######")

# Get the current temperature of the thermostat
print thermostat.fahrenheit
```

The output:

[root@docker python-nuheat]# python nuheat.py 
No handlers could be found for logger "nuheat.api"
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "nuheat.py", line 10, in <module>
    print thermostat
  File "/root/python-nuheat/nuheat/thermostat.py", line 35, in __repr__
    self.fahrenheit,
  File "/root/python-nuheat/nuheat/thermostat.py", line 48, in fahrenheit
    return nuheat_to_fahrenheit(self.temperature)
  File "/root/python-nuheat/nuheat/util.py", line 58, in nuheat_to_fahrenheit
    return int(round_half(((nuheat_temperature - 33) / 56.0) + 33))
  File "/root/python-nuheat/nuheat/util.py", line 10, in round_half
    return Decimal(number).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
  File "/usr/lib64/python2.6/decimal.py", line 649, in __new__
    "First convert the float to a string")
TypeError: Cannot convert float to Decimal.  First convert the float to a string

Pretty sparse out there for NuHeat API libraries - thanks for working on this. Hoping to eventually query the thermostat and dump its data into my home Grafana instance!

**Comment by broox** [comment]
i see you're running this in **python2.6**. i unfortunately only tested back to 2.7 with a focus on python3.

your version of python may or may not be relevant to this bug, but i'll try to get it addressed regardless. thanks for reporting the issue!

**Comment by broox** [comment]
@yetdog i copied your example script and mine seemed to work appropriately on python 2.7 at my house. i also noticed from your stack trace that it seemed to be erroring out on a line with `print thermostat`, so i added that to my file as well, just to be sure.

```
$ python yetdog.py
<NuHeatThermostat id='XXXXX' temperature='79F / 26C' target='80F / 27C'>
79
```

and just to verify, i added [an additional test](https://github.com/broox/python-nuheat/commit/3a18852dc9465c34cb96eb3a0c84f1a6caa70707) to prove that everything is working accordingly in 2.7 and above. 

SO, after a bit more digging, it looks as though rounding floating point numbers was absolutely an issue with **python 2.6** according to the [What's new](https://docs.python.org/3/whatsnew/2.7.html) page for **python 2.7**.

> Conversions between floating-point numbers and strings are **now correctly rounded** on most platforms. These conversions occur in many different places: str() on floats and complex numbers; the float and complex constructors; numeric formatting; serializing and deserializing floats and complex numbers using the marshal, pickle and json modules; parsing of float and imaginary literals in Python code; and **Decimal-to-float conversion**.

i'd like to not add support for a nearly decade old version of python if possible. are you able to upgrade to 2.7?

**Comment by yetdog** [comment]
Thanks @broox  - sorry for the delay. Yes indeed 2.7 works! Very happy with this access - thanks again!

**Comment by broox** [comment]
great!
