### ISSUE TITLE
Mape Heat Alternative URL

### ISSUE THREAD

**Issue by brab** [broox/python-nuheat#4]
NuHeat was recently rebranded as Mape Heat and has correspondingly changed their domain name. It seems likely that the API at the new URL is the same as the old one, but registration with new devices under the new brand happens there instead. I believe that old devices will continue to function at the old NuHeat domain.

Old API URL: https://mynuheat.com/api OR https://www.mynuheat.com/api (with optional www subdomain)
New API URL: https://mymapeheat.com/api OR https://www.mymapeheat.com/api (with optional www subdomain)

Since it appears that both URLs should be supported for the time being, it would be ideal if the choice were an option in config.py or taken as an argument to the NuHeat() constructor.

**Comment by brab** [comment]
I'm trying to use the [NuHeat HA integration](https://www.home-assistant.io/integrations/nuheat/) for my new thermostat, which uses this library for the connection and control. Unfortunately my new thermostat is Mape Heat branded and is registered through the new domain so I'm stuck for the moment.

Before I put any more energy into making this library work I'd like to know if you're considering PRs or interested in maintaining it yourself. I'd like to get my thermostat working so either way I'm likely to fork this repo and make some changes but if you'd consider a PR I'll put a little more work into making it configurable, whereas if you wouldn't then I'll just edit the URL for my own use.

Thanks for your work to get this running a few years ago! :)

**Comment by broox** [comment]
PRs are definitely welcome!

**Comment by dapostol73** [comment]
Any update on this getting support in? I too would like to use MapeHeat with Home Assistant.

**Comment by brab** [comment]
I apologize; this fell completely off my radar. @dapostol73's comments on my PR are pretty manageable so I'll try to get to them in the next couple of weeks. It'd be good to finally get this merged so it can be picked up by HA.

**Comment by broox** [comment]
@brab - let me know if i can help! also, would you mind rebasing your branch from `master`? i've added some github workflows to automate testing. thanks!

**Comment by dapostol73** [comment]
@brab is there any way I can test these changes...happy to help verify it works.

**Comment by brab** [comment]
Hey folks. Sorry for the major delay on this one. I left on vacation shortly after my last comment and then came down with a fairly bad case of COVID. I did take a look at it a few weeks back and it shouldn't be too bad to refactor and get to a merge-ready state, I just need to find some time to get to it.

**Comment by brab** [comment]
Thanks for carrying this over the finish line, @broox! I'm excited to see this get into HomeAssistant now. 😄

**Comment by broox** [comment]
yay!

**Comment by broox** [comment]
hey @brab, would you mind giving me a JSON dump of what `data` looks like in the `thermostat.get_data()` function for the Mape thermostat?

I'd like to add a fixture specifically for Mape so that we can make sure we're testing for and supporting all of its features.

**Comment by brab** [comment]
Sounds like a good idea. [Here you go](https://github.com/broox/python-nuheat/files/10485624/thermostat_data.txt).

**Comment by dapostol73** [comment]
Are there instructions on how to set this up on Home Assistant?  Was hope the NuHeat Integration would expose this but doesn't look like it.

Looks like there is some issue with the release to PyPi based on this post.
https://github.com/home-assistant/core/issues/122675#issuecomment-2254295005
